name: 'Create Umbraco ZIP Package'
description: 'A GitHub action to use in workflows to help automate creating an Umbraco ZIP package for the C# OpenSource CMS Umbraco'
author: 'WarrenBuckley'
inputs:
  packageXmlPath:
    description: 'The path to the Umbraco Package.xml that we use to build the package'
    default: 'build/package.xml'
    required: true

  packageFilesPath:
    description: 'The path to the folder containing all the files needed for the package, excluding the package.xml'
    default: 'build.tmp.package'
    required: true

  packageVersion:
    description: 'A version for the Umbraco package such as 1.3.2'
    required: true

runs:
  using: 'node12'
  main: 'lib/main.js'

branding:
  icon: 'box'
  color: 'purple'